version: "3.3"

services:
  object_detect:
    build: .
    # image: object_detect
    ports:
    - "8888:8888"
    entrypoint: python server.py
    networks:
      od_net:
        ipv4_address: 172.20.0.3

networks:
  od_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16